---
- name: Add Docker’s official GPG key
  ansible.builtin.command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  become:

- name: Install Docker
  raw: sudo apt-get update && sudo apt-get install -y docker.io
